version: '3.8'

services:
  app:
    build: .
    image: sudharsan30/prod:${TAG:-latest}
    container_name: devops-build-web-1
    ports:
      - "80:80"
    networks:
      - devops-build-network

networks:
  devops-build-network:
    name: devops-build_default
