services:
  app:
    image: sudharsan30/prod:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - FLASK_ENV=production
networks:
  default:
    name: devops-build_default
